// Code generated by "stringer -type StatusType"; DO NOT EDIT.

package service

import "strconv"

const _StatusType_name = "STOPPEDPARTIALRUNNING"

var _StatusType_index = [...]uint8{0, 7, 14, 21}

func (i StatusType) String() string {
	if i >= StatusType(len(_StatusType_index)-1) {
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusType_name[_StatusType_index[i]:_StatusType_index[i+1]]
}
